#! /usr/bin/env node
require('babel-polyfill');
var logger = require('./logging');
var parseOptions = require('./cli/argv');
var parsers = require('./parsers');
var schemas = require('./schemas');

var exitCode = 0;

try {
  var options = parseOptions(process.argv);

  var pendingOperations = [];
  var parse = parsers[options.mediaType];

  logger.info(["Parsing", options.type, "from file at:", options.path].join(' '));

  parse(options)
    .on('row', function(row) {
      pendingOperations.push(schemas[options.type](row));
    })
    .on('done', function() {
      Promise.all(pendingOperations).then(function() {

        logger.info('Done, good bye!');
        process.exit(exitCode);

      }).catch(function(exception) {

        logger.error(exception);
        process.exit(exitCode++);

      });
    });

} catch (exception) {
  logger.error(exception);
  process.exit(exitCode++);
}
