##### Authentication

### Logging A User In with CGI Credentials

POST http://{{host}}:{{port}}/login
Content-Type: application/json

{
    "email": "superuser@cgi.com",
    "password": "P@$$w0rd"
}

### Logging A User in with Google Credentials

POST http://{{host}}:{{port}}/login/google
Content-Type: application/json

{
    "code": "google-onetime-auth-code",
}

### Logging A User in with Facebook Credentials

POST http://{{host}}:{{port}}/login/facebook
Content-Type: application/json

{
    "code": "facebook-onetime-auth-code",
}

##### Users

### Fetch all users

GET http://{{host}}:{{port}}/users
Authorization: {{token}}
Accept: application/json

### Fetch a specific user by their user ID
GET http://{{host}}:{{port}}/users/aaa09b7b-a2a6-40b2-93e8-92f1c8de8501
Authorization: {{token}}
Accept: application/json


### Update an existing user
PUT http://{{host}}:{{port}}/users/aaa09b7b-a2a6-40b2-93e8-92f1c8de8501
Authorization: {{token}}
Accept: application/json

{
    "email": "someuser@cgi.com"
}

### Update an existing user telephone number
PUT http://{{host}}:{{port}}/users/aaa09b7b-a2a6-40b2-93e8-92f1c8de8501/telephones/c60f27d5-c53a-4fce-94fa-d7afd388cd81
Authorization: {{token}}
Accept: application/json

{
    "extension": "4423"
}
### Update an existing user telephone number

POST http://{{host}}:{{port}}/users/aaa09b7b-a2a6-40b2-93e8-92f1c8de8501/addresses
Authorization: {{token}}
Accept: application/json

{
    "type": "9e985ff6-9636-1d2f-474a-a871c584f94b",
    "street": "1283 Someplace Dr.",
    "city": "Springfield",
    "state": "CO",
    "postalCode": "80874"
}
### Add a telephone to an existing user
POST http://{{host}}:{{port}}/users/aaa09b7b-a2a6-40b2-93e8-92f1c8de8501/telephones
Authorization: {{token}}
Accept: application/json

{
    "countryCode": "011",
    "areaCode": "303",
    "number": "1234567",
    "extension": "1234",
    "type": "ec52098f-9ad6-230c-42a7-20ecc40bfe6c"
}