#%RAML 1.0
title: CGI Web Services
baseUri: http://api.commongatewayinternational.com
mediaType:
  - application/json
protocols:
  - HTTP
types:
  User: !include types/user.raml
  Nationality: !include types/nationality.raml
  Choice: !include types/choice.raml
  Category: !include types/category.raml
  Term: !include types/term.raml
  TermExclusion: !include types/term-exclusion.raml
  Language: !include types/language.raml
  Telephone: !include types/telephone.raml
  Examination: !include types/examination.raml
  ExaminationSection: !include types/examination-section.raml
  ExaminationQuestion: !include types/examination-question.raml
  MultipleChoiceQuestion: !include types/multiple-choice-question.raml
  CategoryMatchingQuestion: !include types/category-matching-question.raml
  TermMatchingQuestion: !include types/term-matching-question.raml
traits:
  secured: !include traits/secured.raml
version: v1.0
/users: !include resources/users.raml
/nationalities: !include resources/nationalities.raml
/choices: !include resources/choices.raml
/categories: !include resources/categories.raml
/terms: !include resources/terms.raml
/examinations: !include resources/examinations.raml
